### ISSUE TITLE
Coverage is below 90%

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/alppaca#27]
We should increase this a little, especially for this component.

**Comment by schlomo** [comment]
What is the business value of a high coverage number?

**Comment by esc** [comment]
The business value is more stability when adding new features because existing ones are less likely to break. While high coverage isn't the goal per-se, low coverage does indicate that tests may be missing.

**Comment by schlomo** [comment]
Please define "low" and "high". 90% sounds quite high to me...

**Comment by esc** [comment]
It's all in the eye of the beholder!

**Comment by esc** [comment]
FWIW: for the more recent projects we have achieved 100% coverage.

**Comment by esc** [comment]
Maybe you want to rename this issue to: double check unit tests and add more in case we need them.

**Comment by schlomo** [comment]
Well, it _is_ your issue, actually.

**Comment by snordhausen** [comment]
The parts of the code that get unit tested have 99% coverage. Integration tests take care of the remaining parts, but that's not counted for the coverage.

What does not get tested by either unit or  integration tests are
- some error conditions in util.py
- set up of the AssumeRoleCredentialProvider in main.py

The error conditions would be fatal, anyway. Testing if the credential provider is really set up correctly for the assume role feature is... tricky. So I'd say things are tested reasonably well.

**Comment by esc** [comment]
OK, would be nice to include the coverage of the integration tests too, not sure if pybuilder can do that. @mriehl what do you say?

**Comment by mriehl** [comment]
@esc I somehow missed this mention, sorry. Each integration test runs out of process (with a completely separate python interpreter instance), so it would be a matter of measuring coverage for each test and then somehow merging it together. I don't know if any work has been done in that area, but it sure sounds complicated.

Personally I think that including integration tests in coverage data is kind of a gray zone in many cases because while the code is executed there is usually no guarantee that what the code does is expected (you can't assert on everything, so it's more like the "it compiles" from a statically typed language).
