### ISSUE TITLE
alppaca to automatically re-read it's own config if this changes.

### ISSUE THREAD

**Issue by esc** [ImmobilienScout24/alppaca#30]
We want to allow alppaca to run without interruption. Instead of manually doing a restart it might be nice to allow alppaca to use inotify to watch it's own config direcatory and files:

https://pypi.python.org/pypi/inotify/0.2.4

**Comment by range** [comment]
This one should be closed. It makes more sense to let your orchestration/deployment chain handle this, as an automatic restart might leave your application in a broken state.

Scenario: Config gets deployed -> restart fails, because config is broken -> deployment chain does not see this and thinks deployment went fine -> rest of the application gets deployed and everything is red, although the deployment was green.

**Comment by esc** [comment]
Yeah, closing now.
